#ifndef EXTUTIL_VERSION_H_
#define EXTUTIL_VERSION_H_

#include "preprocessor.h"

#define EXTUTIL_MAJOR_VERSION 0
#define EXTUTIL_MINOR_VERSION 1
#define EXTUTIL_BUILD_NUMBER 0
#define EXTUTIL_PATCH_LEVEL 0

#if EXTUTIL_PATCH_LEVEL > 0
#define EXTUTIL_VERSION_STRING \
    EXTUTIL_MK_STR(EXTUTIL_MAJOR_VERSION) "." EXTUTIL_MK_STR(EXTUTIL_MINOR_VERSION) "." EXTUTIL_MK_STR(EXTUTIL_MINOR_VERSION) "." EXTUTIL_MK_STR(EXTUTIL_PATCH_LEVEL)
#else
#define EXTUTIL_VERSION_STRING \
    EXTUTIL_MK_STR(EXTUTIL_MAJOR_VERSION) "." EXTUTIL_MK_STR(EXTUTIL_MINOR_VERSION) "." EXTUTIL_MK_STR(EXTUTIL_MINOR_VERSION)
#endif

#define EXTUTIL_VER_PREREQ(major, minor, build, patch) \
    (EXTUTIL_MAJOR_VERSION * 1000000 + EXTUTIL_MINOR_VERSION * 10000 + EXTUTIL_BUILD_NUMBER * 100 + EXTUTIL_PATCH_LEVEL >= ((major)*1000000 + (minor)*10000 + (build)*100 + patch))
#endif // !EXTUTIL_VERSION_H_
